[package]
name = "newsletter"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter"

[dependencies]
actix-web = "4.3.1"
reqwest = "0.11.17"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
